#ifndef NERD_BASE_COMPLEXITYCLASS_HPP
#define NERD_BASE_COMPLEXITYCLASS_HPP

#include "api.hpp"

namespace nerd {
namespace base {

	enum NERD_BASE_API ComplexityClass {
		CC_CONST,
		CC_NCONST,
		CC_CONSTSPACE,
		CC_NCONSTSPACE,
		CC_LOG,
		CC_NLOG,
		CC_LOGSPACE,
		CC_NLOGSPACE,
		CC_LIN,
		CC_NLIN,
		CC_LINSPACE,
		CC_NLINSPACE,
		CC_LOGLIN,
		CC_NLOGLIN,
		CC_LOGLINSPACE,
		CC_NLOGLINSPACE,
		CC_P,
		CC_NP,
		CC_PSPACE,
		CC_NPSPACE = CC_PSPACE,
		CC_EXP,
		CC_NEXP,
		CC_EXPSPACE,
		CC_NEXPSPACE = CC_EXPSPACE
	};

}}

#endif /* NERD_BASE_COMPLEXITYCLASS_HPP */
